[package]
name = "idgaf"
version = "0.3.0"
authors = ["Mattias Cibien <mattias@mattiascibien.net>"]
edition = "2018"

[dependencies]
clap = { version = "4.4", features = ["cargo"] }
sanitize-filename = "0.5"
pentry = "0.1"